version: '3.8'

services:
  delete-user-service:
    container_name: delete-user-service
    image: stevenbenalcazar/delete-user-service:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://52.91.20.54:5432/taskify_db
      - SPRING_DATASOURCE_USERNAME=taskify_user
      - SPRING_DATASOURCE_PASSWORD=super_secure_password
    ports:
      - "8080:8080"
    networks:
      - taskify-network

networks:
  taskify-network:
    driver: bridge
